name: GitHub Actions Demo
run-name: Test the add functionality 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Looking up repo
        uses: actions/checkout@v4
      - name: Setting up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: going into the right directory
        run: cd src
      - name: running the test file
        run: npm test
        