name: GitHub Actions Demo
run-name: Test the add functionality 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Looking up repo
          uses: actions/checkout@v4
      - name: Setting up NodeJs
          uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: testing calculating with the '+' operator
        run: cd src
        run: npm test
        