name: GitHub Actions Demo
run-name: Test the add functionality 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: testing the add functionality
        run: |
              npm run test
        